version: "3.7"

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true

services:
  db:
    image: postgres
    restart: always
  secrets:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
  environment:
    POSTGRES_DB: /run/secrets/POSTGRES_DB
    POSTGRES_USER: /run/secrets/POSTGRES_USER
    POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD

  app:
    build: webapp
    restart: always
    ports:
      - 5000:8000
  secrets:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
  environment:
    POSTGRES_DB: /run/secrets/POSTGRES_DB
    POSTGRES_USER: /run/secrets/POSTGRES_USER
    POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD

