version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      - PGDB=${PGDB}
      - PGUSR=${PGUSR}
      - PGPWD=${PGPWD}}

  app:
    build: webapp
    restart: always
    ports:
      - 5000:8000
    environment:
      - PGDB=${PGDB}
      - PGUSR=${PGUSR}
      - PGPWD=${PGPWD}}

