version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${PGDS}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPWD}

  app:
    build: webapp
    restart: always
    ports:
      - 5000:8000
    environment:
      - POSTGRES_DB=${PGDS}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPWD}

